name: Mjobs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is test"
  deploy:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is Deploy"
